### ISSUE TITLE
Debug formatting

### ISSUE THREAD

**Issue by theotherphil** [DanielKeep/rust-conv#3] opened 2015-10-10 16:58 UTC
I'm trying to use ValueInto for a conversion that can't fail, so want to unwrap the result (it seems a bit weird that this returns a Result<T, E> at all, rather than just an E). However, I can't call unwrap because: 

affine.rs:120:64: 120:72 note: the method `unwrap` exists but the following trait bounds were not satisfied: `<<<I as image::image::GenericImage>::Pixel as image::buffer::Pixel>::Subpixel as conv::ValueInto<f32>>::Err : core::fmt::Debug`

I had a glance at the code, but can't figure out why the various macros fails to produce error types implementing this trait.

**Comment by DanielKeep** [comment] 2015-10-11 06:52
Well, this looks like a custom conversion, and you haven't given me any indication as to what the involved types are, so I can't reproduce.  What follows are best-guesses:

You say the conversion can't fail: if that's the case, you should be using `NoError` as the error type.  Not only does this *definitely* implement `Debug`, it allows you to use `.unwrap_ok()` to completely bypass the usual unwrapping path.  Actually, if you have a conversion that can't possibly fail, why not use `From`/`Into` instead?

As for why: because you can't pick-and-choose whether or not to return a `Result` on a per-conversion basis.  Either *everything* returns a `Result`, or *nothing* does.

Actually, now that I think about it, the error is talking about a full path to the trait's associated `Err` type.  The traits don't *enforce* that the `Err` types are *actually* errors; they're unconstrained.  Because of that, if you were to use said conversion in a generic function, you'd probably *have* to add a constraint that `Err` implements `Error` (or at least `Debug`).

Hmm...

It *might* be worth adding the constraint to the associated type, since there's not really any reason to *not* use proper error types there.  I'll try it out and see what happens.

**Comment by DanielKeep** [comment] 2015-10-11 07:19
I made the change (see the f0e9f6b commit on the working branch), which doesn't appear to break any of the existing "built-in" conversions.  That said, it *will* break any user-defined conversions where the `Err` type doesn't implement `Error`.  As such, I've bumped the version number and will wait a bit for a release, just in case there's something else I can add without needing to bump the version again.

**Comment by theotherphil** [comment] 2015-10-11 07:50
This was in a generic function. I've not defined any of my own conversions. Thanks for adding the Error bound on Err, that fixes my problem.

**Comment by theotherphil** [comment] 2015-10-11 08:08
As for the From/Into question. I didn't think these were implemented for any of the conversions between primitive types in the standard library. And you can't add trait impls for someone else's trait and type, right? I might have got either/both of these slightly/totally wrong and I could have just been using From and Into all along.

**Comment by DanielKeep** [comment] 2015-10-11 08:16
Correct, but the error looked like you were converting a custom type, which you *would* be able to write an implementation for.  Like I said, without actual code, I have to guess at what the problem is/was.

**Comment by theotherphil** [comment] 2015-10-11 08:19
Cool, thanks for clarifying. Yeah, should have included more context.

**Comment by DanielKeep** [comment] 2016-04-05 05:40
Closing because this should have been closed a while ago, but I, uh... forgot?  :S

**Closed by DanielKeep** 2016-04-05 05:40 UTC
